<a href="https://colab.research.google.com/github/yahya16-rey/data-science/blob/main/data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 # CONNECT TO GOOGLE DRIVE
from google.colab import drive
drive.mount('/content/drive')
!find "/content/drive/My Drive" -type f -iname "heart.csv"

Mounted at /content/drive
/content/drive/My Drive/dataset/heart.csv

In [ ]:

import pandas as pd
df = pd.read_csv("/content/drive/My Drive/dataset/heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
df2 = df[(df['age']>40)&(df['age']<50)]
df2

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2,1
12,49,1,1,130,266,0,1,171,0,0.6,2,0,2,1
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
280,42,1,0,136,315,0,1,125,1,1.8,1,0,1,0
285,46,1,0,140,311,0,1,120,1,1.8,1,2,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0

In [ ]:
x = df.iloc[:, 0:13]
y = df.iloc[:, 13]
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.1)
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
186,60,1,0,130,253,0,1,144,1,1.4,2,1,3
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3
113,43,1,0,110,211,0,1,161,0,0.0,2,0,3
217,63,1,0,130,330,1,0,132,1,1.8,2,3,3
180,55,1,0,132,353,0,1,132,1,1.2,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
274,47,1,0,110,275,0,0,118,1,1.0,1,1,2
189,41,1,0,110,172,0,0,158,0,0.0,2,0,3
185,44,1,0,112,290,0,0,153,0,0.0,2,1,2
194,60,1,2,140,185,0,0,155,0,3.0,1,0,2

In [ ]:
# Model klasifikasi data yang dapat memisahkan hasilnya
from sklearn.svm import SVC
clf = SVC ()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred, y_test))

0.7741935483870968